<?php
//$Id$

/**
* hook_menu() implementation
*
*/
function imgimport_menu() {
  $items = array();
  $items['imgimport']=array(
    'title' => t('Image import'),
    'description' => t(''),
    'page callback'=>'imgimport_import',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'weight' => 0,
    'type' => MENU_NORMAL_ITEM
  );
  return $items;
}


/**
* batch operations initialization
*
*/
function imgimport_import() {
  $bundles = imgimport_get_bundles();
  $list = imgimport_get_node_list('notebook');
  dsm($list);
  return "11111";
}

/**
*  Get bundles list for products
*
*/
function imgimport_get_bundles() {
  $bundles = db_query("SELECT pr.bundle FROM {field_data_field_product_relation} pr GROUP BY pr.bundle")->fetchAll();
  return $bundles;
}

/**
* Gen node list by bundle
*
*/
function imgimport_get_node_list($bundle = NULL) {
  if ($bundle != NULL) {
    $nodes = db_query("
	SELECT n.nid, cp.sku
	FROM {commerce_product} cp, {node} n 
	INNER JOIN {field_data_field_edit_status_relation} ed ON (ed.entity_id = n.nid AND ed.field_edit_status_relation_tid = '104')
	INNER JOIN {field_data_field_product_relation} pr ON (pr.entity_id = n.nid)
	WHERE n.type = :bund AND cp.product_id = pr.field_product_relation_product_id
	", array(':bund'=>$bundle))->fetchAll();
  }
  return $nodes;
}

