<?php
//$Id$

/**
* hook_menu() implementation
*
*/
function imgimport_menu() {
  $items = array();
  $items['imgimport']=array(
    'title' => t('Image import'),
    'description' => t(''),
    'page callback'=>'imgimport_import',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'weight' => 0,
    'type' => MENU_NORMAL_ITEM
  );
  return $items;
}


/**
* menu item handler
*
*/
function imgimport_import() {
  $bundles = imgimport_get_bundles();
  imgimport_batch_init($bundles);
  return "Completed";
}

/**
* batch process initialization
*
*/
function imgimport_batch_init($bundles) {
  $batch = array(
    'title'=>t('Image import'),
	'operations' => array(
	  array('imgimport_img_process', array($bundles)),
	),
	'finished' => 'imgimport_batch_finished',
  );
  batch_set($batch);
  batch_process('/');
}

/**
* Batch processing function
*
*/
function imgimport_img_process($bundles, &$context) {
 //On start initialization 
 if (empty($context['sandbox'])) {
    $context['sandbox']['progress'] = 0;
	$context['sandbox']['current_bundle_count'] = 0;
	$context['sandbox']['max'] = sizeof($bundles);
	dsm($bundles);
  }
  
  $list = imgimport_get_node_list($bundles[$context['sandbox']['current_bundle_count']]->bundle);
  foreach ($list as $pos) {
    imgimport_update_image_by_nid($pos->nid, $pos->sku, $bundles[$context['sandbox']['current_bundle_count']]->bundle);
  }
  
  $context['sandbox']['current_bundle_count']++;
  $context['sandbox']['progress']++;
  
  //End of import checking
  if ($context['sandbox']['progress'] != $context['sandbox']['max']) {
    $context['finished'] = $context['sandbox']['progress'] / $context['sandbox']['max'];
  }
}

/**
* Batch end function
*
*/
function imgimport_batch_finished($success, $results, $operations) {
  drupal_set_message("Import process finished");
}

/**
*  Get bundles list for products
*
*/
function imgimport_get_bundles() {
  $bundles = db_query("SELECT pr.bundle FROM {field_data_field_product_relation} pr GROUP BY pr.bundle")->fetchAll();
  return $bundles;
}

/**
* Gen node list by bundle
*
*/
function imgimport_get_node_list($bundle = NULL) {
  if ($bundle != NULL) {
    $nodes = db_query("
	SELECT n.nid, cp.sku
	FROM {commerce_product} cp, {node} n 
	INNER JOIN {field_data_field_edit_status_relation} ed ON (ed.entity_id = n.nid AND ed.field_edit_status_relation_tid = '104')
	INNER JOIN {field_data_field_product_relation} pr ON (pr.entity_id = n.nid)
	WHERE n.type = :bund AND cp.product_id = pr.field_product_relation_product_id
	", array(':bund'=>$bundle))->fetchAll();
  }
  return $nodes;
}

/**
* Image insert by nid and sku
*
*
*/
function imgimport_update_image_by_nid($nid, $sku, $bundle) {
  if (isset($nid) && isset($sku) && isset($bundle)) {
    
	//copy img file to destination directory
    $file = imgimport_copy_image($bundle, $sku);
	if ($file != NULL) {
	      $node = node_load($nid);
		  if (sizeof($node->field_product_image) == 0) {
		    $node->field_product_image['uk']['0'] = (array)$file;
		    node_save($node);
		  }
	}	
  }
}

/**
* Copy image from temporary directory to destination directory
*
*/
function imgimport_copy_image($bundle, $sku) {
  $file = NULL;
  if (isset($bundle) && isset($sku)) {   
	
	$file_path = drupal_realpath('sites/default/files/_temp_images_to_import_by_val/'.$sku.'.jpg');

	if ($file_path != NULL) {
	
	  $file = (object)array(
        'uid' => 1,
        'uri' => $file_path,
        'filename' => basename($file_path),
        'filemime' => file_get_mimetype($file_path),
      );
	  
	  $file = file_copy($file, 'public://product_img/'.$bundle);
	}
  }
  return $file;
}
